defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
  -
    scope:
      path: ""
      type: "defaults"
    values:
      layout: "bootstraps" # overrides previous default layout
      author: "Bootstraps.com"
